apiVersion: v1
kind: Service
metadata:
  name: np-frontend
  namespace: dhaka
spec:
  ports:
  - nodePort: 30100
    name: npf-fr-dh-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: np-frontend
  type: NodePort
